### ISSUE TITLE
Set custom value to queryKey

### ISSUE THREAD

**Issue by himaratsu** [connectrpc/connect-query-es#454]
# Problem

connect-web automatically makes queryKey, it is useful in many cases.
But, I may have issue for controlling cache.

This is an example of Todo app.

**queryKey of Todo List**
```
["example.v1.Service", "GetTodos"]
```

queryKey of Todo Detail**
```
["example.v1.Service", "GetTodo", {id: "xxx"}]
```

The second element is methodName.
Because this is different, invalidating the list does not discard the details cache.

# Proposal

Can we extend `useQuery` function to set an arbitrary queryKey?

**Comment by paul-sachs** [comment]
Hi @himaratsu. This behaviour is by design, we do it to provide strict type safety. You can of course use [createQueryOptions](https://github.com/connectrpc/connect-query-es?tab=readme-ov-file#createqueryoptions) directly and override the queryKey if you want to, but it opens you up for potential type mismatches.

If I understand your meaning, you want to invalidate more than one query with a call to `invalidateQueries`. One way to do this while maintaining the integrity of the key/value relationship would be to use `predicate` like so:

```tsx
queryClient.invalidateQueries({
  predicate: (query) => {
     const queryKey = query.queryKey as ConnectQueryKey<AnyMessage>;
     return queryKey[1] === methodDescriptor.name || queryKey[1] === methodDescriptor.name
   },
})
```

We should have a slightly more robust and typesafe way to operate on the queryclient after v2 is released but this should do for now.
This behaviour will likely change in v2 since we're improving the keys

**Comment by himaratsu** [comment]
Hi paul-sachs , Thank you for your help.
I’ll try it!
