### ISSUE TITLE
 What is the best way to implement stream?

### ISSUE THREAD

**Issue by himaratsu** [connectrpc/connect-query-es#471]
## What I want to do

* I'm developing Todo app
* Multiple members can create and edit tasks at the same time
* When changes are made, other members receive it in real-time and the task is updated.

## My understanding 
* connect-query does not support streams and cannot be implemented

## Question
* Can I use connect-web in parallel with connect-query?
  * Or is there a better way?

Thanks!

**Comment by paul-sachs** [comment]
Hi @himaratsu, you can use connect-web along with connect-query, no problem. Connect-query itself doesn't support streaming because the underlying @tanstack/query doesn't provide a sufficient primitive to work with streams consistently. There are a few ideas that have been bounced around in #225 #31 that might provide some ideas.

**Comment by himaratsu** [comment]
Thank you for your advice! I'll try using connect-web.

In my opinion, stream is one of the key elements of gRPC(Connect), and supporting it will benefit library users more than being consistent with @tanstack/query.

Thank you for great work!
