### ISSUE TITLE
Support NextJS RSC

### ISSUE THREAD

**Issue by paul-sachs** [connectrpc/connect-query-es#55]
Currently all the apis exposed depend on context to get the transport. This causes issues with React Server Components. One potential solution to this problem would be to create a context free generated version of the apis that requires the transport as an argument.

**Comment by ImSingee** [comment]
I think this (support react-query hydration) will be helpful.

However, apart from the dependent on context, one of the annoying reasons is that RSC only allows passing down raw objects, but `Message` in protobuf-es is a class.

Maybe the `select` function in react-query is useful (pass down json only and de-serialize it in client.

**Comment by paul-sachs** [comment]
@ImSingee yeah, I think the plan would be to use the `toPlainMessage()` from `@bufbuild/protobuf` (introduced [here](https://github.com/bufbuild/protobuf-es/pull/511)) to simplify. I'm not sure `select` is the best place, cus that assumes the cache has the class based message, but what we're serializing is actually a plain message/object so i think we just need to modify the queryFn/mutationFn to serialize using `toPlainMessage()`

**Comment by ImSingee** [comment]
@paul-sachs Thanks for your information. However, I don't think we can bypass using `select` if we don't want to introduce a breaking change. `PlainMessage` is a raw object, but `Message` is a class, changing the return type of the queryFn will break many existing type annotations and even functions.

I think, in the current queryFn we should still return a `Message`, and we can provide an additional function that may be called `prefetchQuery` and return `PlainMessage` in that. We should also detect the type in `useQuery`'s queryFn and auto convert the `PlainMessage` to `Message`.

This won't be a breaking change since the package never supports RSC. Though we add a `select` method, it's in fact a no-op in the client side so doesn't break anything (e.g. custom select method).

**Comment by ImSingee** [comment]
I have tried `toPlainMessage`, but it still fails with reason `Do not know how to serialize a BigInt`. So I revert to use `fromJson` and `toJson` now.

**Comment by paul-sachs** [comment]
@getinnocuous you can use Connect with RSC, you just have to make sure whatever gets serialized is serialized with `toPlainMessage()` and deserialized by passing through the proper class constructor. Until nextjs/RSC support a way to customize serialization/deserialization, that's going to have to be handled in user space.

**Comment by paul-sachs** [comment]
Actually, that may not be correct. I think RSC isn't supposed to handle serialization/deserialization at all (https://nextjs.org/docs/app/building-your-application/configuring/typescript#end-to-end-type-safety), so it's really just a matter of how to prime the react-query cache specifically. This seems to be a larger question around the react-query community that I haven't seen an answer to yet.

**Comment by paul-sachs** [comment]
With V2 out, the data serialized into the cache is now just plain objects so any hydration process will be near identical to the recommended way to do it in react-query. For a connect specific SSR serialization example, see [here](https://connectrpc.com/docs/web/ssr/).
